[package]
name = "evocraft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4.2"
macroquad-tiled = "0.2.0"
rand = "0.8.5"
grid = "0.10.0"
perlin2d = "0.2.6"
rayon = "1.8.0"

